spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fastta?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
    redis:
      host: localhost
      port: 6379

fastta:
  upload-path: default
  manage:
    employee-default-password: 123456

aliyun:
  sms:
    accesskey-id: default
    accesskey-secret: default
    msg-template: default
    enable: false