spring:
  shardingsphere:
    datasource:
      names: ds-master,ds-slave
      ds-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.56.102:3306/fastta?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: armin
        password: armin
      ds-slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.56.103:3306/fastta?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: armin
        password: armin
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ds
      master-data-source-name: ds-master
      slave-data-source-names: ds-slave #从库数据源名称列表，多个用逗号分隔
    props:
      sql:
        show: true

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

fastta:
  upload-path: default
  manage:
    employee-default-password: 123456

aliyun:
  sms:
    accesskey-id: default
    accesskey-secret: default
    msg-template: default
    enable: false