server:
  port: 8888
  servlet:
    context-path: /fastta

spring:
  application:
    name: fastta
  profiles:
    active: dev
  cache:
    redis:
      time-to-live: 1800000
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    # map-underscore-to-camel-case: table_name <--> ClassName, column_name <--> attributeName
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
    banner: false

security:
  ignored:
    urls: #SpringSecurity过滤白名单
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.jpg
      - /**/*.ico
      - /**/*.woff2
      - /**/*.woff
      - /**/*.ttf
      - /**/*.map
      - /employee/login
      - /employee/logout
      - /user/sms
      - /user/login
      - /**/*.otf

